# Generated by Django 5.2.3 on 2025-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('application_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('battery_voltage', models.FloatField(null=True)),
                ('battery_status', models.IntegerField(null=True)),
                ('external_sensor', models.CharField(max_length=128, null=True)),
                ('humidity', models.FloatField(null=True)),
                ('temp_sht', models.FloatField(null=True)),
                ('temp_ds', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('raw_payload', models.JSONField()),
            ],
        ),
    ]
