# Generated by Django 5.2.3 on 2025-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_enddevice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorkerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='device name', max_length=100)),
                ('url_path', models.CharField(default='v3/humidity', max_length=100)),
                ('gateway_path', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enddevice',
            name='gateway_path',
        ),
        migrations.RemoveField(
            model_name='enddevice',
            name='url_path',
        ),
        migrations.AddField(
            model_name='enddevice',
            name='image_path',
            field=models.CharField(default='image path', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='device_name',
            field=models.CharField(default='device name', max_length=100),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='device_status',
            field=models.CharField(default='device status', max_length=10, null=True),
        ),
    ]
