# Generated by Django 5.2.3 on 2025-08-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_borkerconnection_gateway_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='battery_status',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='battery_voltage',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='external_sensor',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='temp_ds',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='temp_sht',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='application_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='device_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='raw_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
