# Generated by Django 5.2.3 on 2025-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_enddevice_sensorreading_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
