# Generated by Django 5.2.3 on 2025-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_borkerconnection_remove_enddevice_gateway_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borkerconnection',
            name='gateway_path',
            field=models.CharField(default='gateway path', max_length=100, null=True),
        ),
    ]
