# Generated by Django 5.2.3 on 2025-08-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_remove_sensorreading_battery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borkerconnection',
            name='sensor_type',
            field=models.CharField(default='humidity', max_length=100, null=True),
        ),
    ]
