# Generated by Django 5.2.3 on 2025-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_borkerconnection_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddevice',
            name='device_id',
            field=models.CharField(default='device id', max_length=100),
        ),
    ]
