# Generated by Django 5.2.3 on 2025-08-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_enddevice_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ship', max_length=100)),
                ('image_path', models.CharField(default='image path', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enddevice',
            name='position_x',
            field=models.CharField(default='25%', max_length=40),
        ),
        migrations.AddField(
            model_name='enddevice',
            name='position_y',
            field=models.CharField(default='55%', max_length=40),
        ),
        migrations.AddField(
            model_name='enddevice',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='sensors.vehicle'),
        ),
    ]
