# Generated by Django 5.2.3 on 2025-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_vehicle_enddevice_position_x_enddevice_position_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoraGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='lora gateway', max_length=100)),
                ('url_path', models.CharField(default='url path', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
