# Generated by Django 5.2.3 on 2025-08-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_loragateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image_path',
            field=models.ImageField(default='image.png', null=True, upload_to='vehicle_images/'),
        ),
    ]
