# Generated by Django 5.2.3 on 2025-08-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_alter_vehicle_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.vehicle'),
        ),
    ]
