# Generated by Django 5.2.3 on 2025-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_alter_enddevice_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddevice',
            name='dev_eui',
            field=models.CharField(default='00:00:00:00:00:00:00:11', max_length=100),
        ),
        migrations.AddField(
            model_name='enddevice',
            name='join_eui',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
