# Generated by Django 5.2.3 on 2025-08-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_enddevice_dev_eui_enddevice_join_eui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enddevice',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sensors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.vehicle'),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='image_path',
            field=models.ImageField(default='image path', null=True, upload_to=''),
        ),
    ]
