# Generated by Django 5.2.3 on 2025-08-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_remove_enddevice_vehicle_vehicle_sensors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='sensors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.enddevice'),
        ),
    ]
