# Generated by Django 5.2.3 on 2025-08-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_alter_vehicle_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevice',
            name='image_path',
            field=models.ImageField(default='image path', null=True, upload_to='sensor_images/'),
        ),
    ]
