# Generated by Django 5.2.3 on 2025-08-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0016_alter_enddevice_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevice',
            name='dev_eui',
            field=models.CharField(default='00:00:00:00:00:00:00:11', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='join_eui',
            field=models.CharField(default='00:00:00:00:00:00:00:11', max_length=100, null=True),
        ),
    ]
