# Generated by Django 5.2.3 on 2025-08-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0017_alter_enddevice_dev_eui_alter_enddevice_join_eui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='sensors',
        ),
        migrations.AddField(
            model_name='enddevice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_devices', to='sensors.vehicle'),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='position_x',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='position_y',
            field=models.FloatField(default=55.0),
        ),
    ]
