# Generated by Django 5.2.3 on 2025-08-31 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_remove_vehicle_sensors_enddevice_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddevice',
            name='broker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_device', to='sensors.borkerconnection'),
        ),
    ]
