# Generated by Django 5.2.3 on 2025-09-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0019_enddevice_broker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorkerConnection',
            new_name='BrokerConnection',
        ),
    ]
