# Generated by Django 5.2.3 on 2025-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0020_rename_borkerconnection_brokerconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddevice',
            name='application_id',
            field=models.CharField(default='humidity_sensor', max_length=100, null=True),
        ),
    ]
