# Generated by Django 5.2.3 on 2025-09-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0021_enddevice_application_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enddevice',
            name='application_id',
        ),
    ]
