# Generated by Django 5.2.3 on 2025-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0022_remove_enddevice_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddevice',
            name='application_id',
            field=models.CharField(default='humidity_sensor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enddevice',
            name='device_status',
            field=models.CharField(default='device status', max_length=100, null=True),
        ),
    ]
