# Generated by Django 5.2.3 on 2025-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0023_enddevice_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enddevice',
            name='device_status',
            field=models.CharField(default='oneline', max_length=100, null=True),
        ),
    ]
