# Generated by Django 5.2.3 on 2025-09-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0024_alter_enddevice_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enddevice',
            name='last_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
