# Generated by Django 5.2.3 on 2025-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0025_enddevice_last_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoraApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default='application id', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
