# Generated by Django 5.2.3 on 2025-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0026_loraapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loraapp',
            name='application_server_address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loraapp',
            name='description',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loraapp',
            name='join_server_address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loraapp',
            name='name',
            field=models.CharField(default='name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loraapp',
            name='network_server_address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
